[pytest]
# --- PATH SETTINGS ---
# Add --reruns 1 to limit retries to just one retry for failed tests, with a 5-second delay
# --- PATH SETTINGS ---
# Added --alluredir to capture report data and --clean-alluredir to refresh it each run
addopts = -v --alluredir=./allure-results --clean-alluredir
pythonpath = .

# --- EXECUTION SETTINGS ---
testpaths = TestCases
python_files = test_*.py

# --- MARKERS ---
# Custom markers to categorize tests
markers =
    sanity: Quick health checks
    regression: Full system test suite
    flaky: Mark test to re-run on failure

# --- LOGGING CONFIGURATION ---
# Enable logging in the console with the specified format
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# --- TIMEOUTS ---
# Set a default timeout for tests, in seconds (e.g., 5 minutes)
timeout = 300
