[common info]
url = https://www.neetprep.com
shop_url = https://shop.neetprep.com
product_name = HYTS HOME TEST SERIES LATEST EDITION

[locators]
# Website :-Added _XPATH and _ID suffixes to match BasePage logic
#landing Page
landingPage_close_classroom_dialogBox_XPATH =(//span[@aria-hidden='true'])[1]
landingPage_drawerMenu_XPATH =(//span[@class='navbar-toggler-icon'])[1]
landingPage_loginButton_XPATH=(//a[@class='n-navbtn'])[1]

#login Page
login_enterMobileNo_XPATH=(//input[@id='number'])[1]
login_TC_constant_checkBox_XPATH=//input[@id='consentCheckbox']
login_sendOTP_button_XPATH=//span[@id='buttonText']
login_enterOTP_XPATH=//input[@id='code']
login_verifyOTP_XPATH=//button[@id='otp_button']
invalid_OTP_error_message_XPATH=//div[text()="Invalid OTP. Please try again."]

#dashboard
adaptivePractice_XPATH=//div[text()='ADAPTIVE PRACTICE']
scoreBooster_XPATH=//div[text()='Score Booster']
customPracticeButton_XPATH=//div[text()='Custom Practice Session']
generateRevision_XPATH=//div[text()='Generate Revision']
Daily_DPP_XPATH=//div[@class='title-section']

#customPracticePage_newui/SubjectsAndChapters
unfinishTest_close_XPATH=(//*[name()='svg'][@class='stroke-current w-6 h-6 dark:text-gray-500'])[1]
noStartFresh_XPATH=//button[text()="No, Start Fresh"]
resumeTest_Xpath=//button[text()='Resume Test']
viewTestAttempt_XPATH=View Test Attempts
searchBox_XPATH=//input[@id='input-search'] #Cell
cellTopic1_XPATH=(//input[@id='c7907'])[1]
cellTopic2_XPATH=(//input[@id='c7905'])[1]

# shop.neetprep.com web elements
shop_click_search_XPATH=(//*[name()='svg'][@class='modal__toggle-open icon icon-search'])[2]
shop_click_searchBox_CSS=body > div:nth-child(10) > sticky-header:nth-child(25) > header:nth-child(1) > details-modal:nth-child(2) > details:nth-child(1) > summary:nth-child(1) > span:nth-child(1) > svg:nth-child(1)
shop_inputSearchBox_XPATH=(//input[@id='Search-In-Modal-1'])[1]
shop_viewAllSearchResults_XPATH=//button[@role='option']//*[name()='svg']
click_HYTS_SearchResults_XPATH=(//p[@class='predictive-search__item-heading h5'])[1]
shop_addToCart_XPATH=(//button[@id='ProductSubmitButton-template--23396510302519__main'])[1]
shop_checkout_XPATH=(//button[normalize-space()='Check out'])[1]
payNowButton_XPATH=(//button[@id='checkout-pay-button'])[1]
